### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by agronholm**
* Consolidated multiple archs to a single Dockerfile
* Switched to Debian on all archs
* Upgraded PyPy3 to v5.8.0
* Dropped the --node entrypoint argument as unnecessary
* Dropped the exposed port 8000 since the default configuration does not use it
* Dropped the copying of static qemu binaries to images since they're not needed there

### CODE REVIEW

**Comment by agronholm** [comment]
Builds complete for all three archs on my workstation.

**Comment by oberstet** [comment]
because you removed the qemu stuff, this is broken

**Comment by agronholm** [comment]
I don't understand. What exactly is broken? If that is so, can I at least fix it?

**Comment by oberstet** [comment]
needs discussion .. see IRC and https://github.com/crossbario/crossbar-docker/issues/48

**Comment by oberstet** [comment]
@agronholm fwiw/fyi: the contents of this repo has moved to the individual projects repos - this here will be closed.

**Pull request closed without merging**
