### PR TITLE
ARMhf Crossbar

### PR DESCRIPTION
**Pull request by hawkowl**

### CODE REVIEW

**Comment by hawkowl** [comment]
cc @oberstet 

screen shot 2016-10-31 at 16 03 01

**Comment by hawkowl** [comment]
@oberstet this makes a much smaller image now (150MB) by using some tricks from https://glyph.twistedmatrix.com/2015/03/docker-deploy-double-dutch.html and some tricks of my own :)

**Comment by hawkowl** [comment]
`crossbario/crossbar-armhf   community           89b2ad22a155        12 minutes ago      147.1 MB`

vs 

`<none>                      <none>              3cbb761b009e        7 hours ago         297.2 MB` before...

**Comment by oberstet** [comment]
@hawkowl fantastic! nice nice .. I will try that when I'm back in the office.

**Pull request merged**
